/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NkSideDrawer {
        "isOpen": boolean;
        "myTitle": string;
    }
}
declare global {
    interface HTMLNkSideDrawerElement extends Components.NkSideDrawer, HTMLStencilElement {
    }
    var HTMLNkSideDrawerElement: {
        prototype: HTMLNkSideDrawerElement;
        new (): HTMLNkSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "nk-side-drawer": HTMLNkSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface NkSideDrawer {
        "isOpen"?: boolean;
        "myTitle"?: string;
    }
    interface IntrinsicElements {
        "nk-side-drawer": NkSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nk-side-drawer": LocalJSX.NkSideDrawer & JSXBase.HTMLAttributes<HTMLNkSideDrawerElement>;
        }
    }
}
